# All paths are relative to this file.

# Paths.
# place the search right next to this file
output_path: './'


# Providers from which to search (case insensitive)
# use indeed only for speed
providers:
#  - 'Indeed'
#  - 'Monster'
  - 'GlassDoor' # This takes ~10x longer to run than the other providers

# Filters.
search_terms:
  region:
    province: 'ON'
    city:     'waterloo'
    domain:   'ca'
    radius:   10

# this search is focused on programming
  keywords:
    - 'Python'
    - 'Java'
    - 'Git'
    - 'Unix'
## Do later, and adjust for Monster
#  experience_level: 
    #- 'intern' # This returns the intern job type on indeed
    #- 'entry'
    #- 'mid'
    #- 'senior'
# exclude these from the search
black_list:
  - 'Infox Consulting'
  - 'Terminal'

# Logging level options are: critical, error, warning, info, debug, notset
# show me only errors
log_level: 'info'

# Save duplicates removed by tfidf filter to a separate csv
save_duplicates: 'False'
